name: check

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: npx eslint src --max-warnings 0
