on: push

name: build

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: cargo build --release
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: target/release
